// <auto-generated />
using System;
using CoteleDunarii.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoteleDunarii.Data.Migrations
{
    [DbContext(typeof(CoteleDunariiContext))]
    [Migration("20211017200431_changedDBContextElements")]
    partial class changedDBContextElements
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoteleDunarii.Data.Models.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Km")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CityId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("CoteleDunarii.Data.Models.WaterEstimations", b =>
                {
                    b.Property<int>("WaterEstimationsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Next120h")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Next24h")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Next48h")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Next72h")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Next96h")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReadTime")
                        .HasColumnType("datetime2");

                    b.HasKey("WaterEstimationsId");

                    b.HasIndex("CityId");

                    b.ToTable("WaterEstimations");
                });

            modelBuilder.Entity("CoteleDunarii.Data.Models.WaterInfo", b =>
                {
                    b.Property<int>("WaterInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Elevation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReadTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Temperature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Variation")
                        .HasColumnType("int");

                    b.HasKey("WaterInfoId");

                    b.HasIndex("CityId");

                    b.ToTable("WaterInfos");
                });

            modelBuilder.Entity("CoteleDunarii.Data.Models.WaterEstimations", b =>
                {
                    b.HasOne("CoteleDunarii.Data.Models.City", "City")
                        .WithMany("waterEstimations")
                        .HasForeignKey("CityId");

                    b.Navigation("City");
                });

            modelBuilder.Entity("CoteleDunarii.Data.Models.WaterInfo", b =>
                {
                    b.HasOne("CoteleDunarii.Data.Models.City", "City")
                        .WithMany("waterInfos")
                        .HasForeignKey("CityId");

                    b.Navigation("City");
                });

            modelBuilder.Entity("CoteleDunarii.Data.Models.City", b =>
                {
                    b.Navigation("waterEstimations");

                    b.Navigation("waterInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
